#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "supabase/seed/generated/us_internal_tax_seed.sql"

SOURCE_VERSION = "us-internal-tax-data-20260524"
CBP_TAX_SOURCE_URL = "https://www.help.cbp.gov/s/article/Article-1114?language=en_US"
USITC_TAX_FAQ_SOURCE_URL = "https://www.usitc.gov/faq/question/what_kinds_taxes_and_fees_are_levied_imports_are.htm"
IRS_EXCISE_SOURCE_URL = "https://www.irs.gov/businesses/small-businesses-self-employed/excise-tax"

EXCISE_CONDITIONS = [
    {
        "condition": "destination_hs_code like '22%'",
        "tax_type": "federal_excise_alcohol",
        "tax_name": "연방 Excise Tax",
        "rate_text": "품목별",
        "basis": "미국 주류 연방 excise tax 후보",
        "notes": "주류는 종류, 알코올 도수, 용량, 수입 목적에 따라 연방 excise tax와 TTB 요건이 달라질 수 있습니다.",
    },
    {
        "condition": "destination_hs_code like '24%'",
        "tax_type": "federal_excise_tobacco",
        "tax_name": "연방 Excise Tax",
        "rate_text": "품목별",
        "basis": "미국 담배류 연방 excise tax 후보",
        "notes": "담배류는 제품 종류, 수량, 포장, 수입자 자격에 따라 연방 excise tax와 TTB/CBP 요건이 달라질 수 있습니다.",
    },
    {
        "condition": "destination_hs_code like '27%' or destination_hs_code like '2901%' or destination_hs_code like '2902%'",
        "tax_type": "federal_excise_fuel",
        "tax_name": "연방 Excise Tax",
        "rate_text": "품목별",
        "basis": "미국 연료·석유제품 연방 excise tax 후보",
        "notes": "연료·석유제품은 제품 조성, 과세연료 여부, 터미널/벌크 이전, 면세 용도에 따라 연방 excise tax가 달라질 수 있습니다.",
    },
    {
        "condition": "destination_hs_code like '4011%' or destination_hs_code like '8701%' or destination_hs_code like '8702%' or destination_hs_code like '8703%' or destination_hs_code like '8704%' or destination_hs_code like '8705%'",
        "tax_type": "federal_excise_vehicle_tire",
        "tax_name": "연방 Excise Tax",
        "rate_text": "품목별",
        "basis": "미국 차량·타이어 연방 excise tax 후보",
        "notes": "일부 중량 차량, 트럭·트레일러, 타이어, 연비 기준 미달 승용차는 조건에 따라 연방 excise tax가 적용될 수 있습니다.",
    },
    {
        "condition": "destination_hs_code like '9303%' or destination_hs_code like '9304%' or destination_hs_code like '9305%' or destination_hs_code like '9306%'",
        "tax_type": "federal_excise_firearms",
        "tax_name": "연방 Excise Tax",
        "rate_text": "품목별",
        "basis": "미국 총기·탄약 연방 excise tax 후보",
        "notes": "총기·탄약류는 제품 분류, 수입자 자격, ATF 요건과 함께 연방 excise tax 적용 가능성을 확인해야 합니다.",
    },
]


def sql(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main() -> None:
    excise_sql = "\n".join(
        f"""
insert into public.export_destination_internal_taxes (
  country_code,
  destination_hs_code,
  tax_type,
  tax_name,
  rate_text,
  basis,
  notes,
  source_name,
  source_url,
  source_version,
  effective_from,
  effective_to,
  published_at,
  retrieved_at,
  status,
  checksum
)
select
  'USA',
  heading.destination_hs_code,
  {sql(row["tax_type"])},
  {sql(row["tax_name"])},
  {sql(row["rate_text"])},
  {sql(row["basis"])},
  {sql(row["notes"])},
  'IRS excise tax',
  {sql(IRS_EXCISE_SOURCE_URL)},
  {sql(SOURCE_VERSION + ':federal-excise')},
  date '2026-01-01',
  null::date,
  null::timestamptz,
  now(),
  'staged'::public.legal_record_status,
  encode(digest('USA|' || heading.destination_hs_code || '|' || {sql(row["tax_type"])} || '|' || {sql(SOURCE_VERSION)}, 'sha256'), 'hex')
from (
  select distinct left(destination_hs_code, 4) as destination_hs_code
  from public.export_destination_tariff_rates
  where country_code = 'USA'
    and source_version = 'usitc-hts-2026-rev7-20260523'
    and ({row["condition"]})
) heading
on conflict (country_code, destination_hs_code, tax_type, tax_name, coalesce(rate_text, ''), source_version)
do update set
  basis = excluded.basis,
  notes = excluded.notes,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  effective_from = excluded.effective_from,
  effective_to = excluded.effective_to,
  published_at = excluded.published_at,
  retrieved_at = excluded.retrieved_at,
  status = excluded.status,
  checksum = excluded.checksum;
"""
        for row in EXCISE_CONDITIONS
    )

    output = f"""-- Generated by scripts/generate_us_internal_tax_seed.py

begin;

delete from public.export_destination_internal_taxes
where country_code = 'USA'
  and source_version like '{SOURCE_VERSION}%';

insert into public.export_destination_internal_taxes (
  country_code,
  destination_hs_code,
  tax_type,
  tax_name,
  rate_text,
  basis,
  notes,
  source_name,
  source_url,
  source_version,
  effective_from,
  effective_to,
  published_at,
  retrieved_at,
  status,
  checksum
)
select
  'USA',
  tariff.destination_hs_code,
  'vat',
  '수입 VAT',
  '없음',
  '미국은 연방 VAT가 없습니다.',
  '미국에는 연방 VAT가 없으며, 주·지방 sales/use tax는 CBP가 수입 통관 단계에서 징수하지 않습니다.',
  'USITC import tax FAQ / CBP taxes on imported goods',
  {sql(USITC_TAX_FAQ_SOURCE_URL)},
  {sql(SOURCE_VERSION + ':no-federal-vat')},
  date '2026-01-01',
  null::date,
  null::timestamptz,
  now(),
  'staged'::public.legal_record_status,
  encode(digest('USA|no-federal-vat|' || tariff.destination_hs_code || '|' || {sql(SOURCE_VERSION)}, 'sha256'), 'hex')
from (
  select distinct destination_hs_code
  from public.export_destination_tariff_rates
  where country_code = 'USA'
    and source_version = 'usitc-hts-2026-rev7-20260523'
) tariff
on conflict (country_code, destination_hs_code, tax_type, tax_name, coalesce(rate_text, ''), source_version)
do update set
  basis = excluded.basis,
  notes = excluded.notes,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  effective_from = excluded.effective_from,
  effective_to = excluded.effective_to,
  published_at = excluded.published_at,
  retrieved_at = excluded.retrieved_at,
  status = excluded.status,
  checksum = excluded.checksum;

insert into public.export_destination_internal_taxes (
  country_code,
  destination_hs_code,
  tax_type,
  tax_name,
  rate_text,
  basis,
  notes,
  source_name,
  source_url,
  source_version,
  effective_from,
  effective_to,
  published_at,
  retrieved_at,
  status,
  checksum
)
select
  'USA',
  tariff.destination_hs_code,
  'state_sales_use_tax',
  '주·지방 Sales/Use Tax',
  '주별',
  '미국 주·지방 sales/use tax 후보',
  'CBP는 수입 물품에 대한 주 sales tax를 징수하지 않습니다. 실제 과세 여부와 세율은 판매·사용 주, 거래 구조, 재판매 여부에 따라 달라질 수 있습니다.',
  'CBP taxes on imported goods',
  {sql(CBP_TAX_SOURCE_URL)},
  {sql(SOURCE_VERSION + ':state-sales-use-tax')},
  date '2026-01-01',
  null::date,
  null::timestamptz,
  now(),
  'staged'::public.legal_record_status,
  encode(digest('USA|state-sales-use-tax|' || tariff.destination_hs_code || '|' || {sql(SOURCE_VERSION)}, 'sha256'), 'hex')
from (
  select distinct destination_hs_code
  from public.export_destination_tariff_rates
  where country_code = 'USA'
    and source_version = 'usitc-hts-2026-rev7-20260523'
) tariff
on conflict (country_code, destination_hs_code, tax_type, tax_name, coalesce(rate_text, ''), source_version)
do update set
  basis = excluded.basis,
  notes = excluded.notes,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  effective_from = excluded.effective_from,
  effective_to = excluded.effective_to,
  published_at = excluded.published_at,
  retrieved_at = excluded.retrieved_at,
  status = excluded.status,
  checksum = excluded.checksum;

{excise_sql}

commit;
"""

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
